### ISSUE TITLE
공통 상세 질문/피드백 컴포넌트 (사이드바)

### ISSUE THREAD

**Issue by minjeongHEO** [minjeongHEO/Job-Cracker#21]
## ✏️ 기능 설명

질문카드를 클릭했을 때, 질문 상세 정보와 답변 피드백을 볼 수 있는 사이드바를 구현합니다.
<br><br>

## ✅ TODO
- [x] 상세 정보 표시 UI
- [x] 사이드바 열리는 애니메이션
- [x] 버튼 클릭 시 사이드바 닫히는 애니메이션
- [x] 질문카드 선택 시 상태 관리 (아직 제목만)

<br><br>

## 📕 참고할만한 자료(선택) 

![image](https://github.com/user-attachments/assets/276323ab-403c-4e97-a8e1-47a59004beda)
