### ISSUE TITLE
GPT API를 사용한 질문 생성 (첫질문, 재질문)

### ISSUE THREAD

**Issue by minjeongHEO** [minjeongHEO/Job-Cracker#22]
## ✏️ 기능 설명
OpenAI API를 사용하여 면접 질문(첫 질문, 다른 주제) 생성 기능 구현 
<br><br>

## ✅ TODO
- [x] openai 패키지
- [x] 프롬프트 설계
- [x] API 통신 구조
- [x] API 응답 구조에 따라 인터페이스 조정 
- [x] 타입 가드를 통한 응답 데이터 검증
- [x] 실제 데이터 연동
- [x] 상태 관리
  - [x] UUID를 통한 키 생성하여 질문 식별
  - [x] 답변과 피드백을 포함한 통합 상태 관리 구조
  - [x] 질문 목록과 선택된 질문 상태 분리

~스트리밍 응답 처리~

<br><br>

### openai 라이브러리
OpenAI에서 직접 만든 공식 라이브러리로 안정성 보장
내장된 타입도 지원하기 때문에 타입스크립트를 사용한 개발 생산성 향상
fetch로 모든로직을 구현하는 것보다 간편하고, 심지어 자동 재시도와 에러 처리도 지원해주기 때문에 도입하였습니다.

### GPT-4o-mini vs GPT-3.5
<img width="780" alt="image" src="https://github.com/user-attachments/assets/2c352ed4-d5ce-4081-9448-921357fdd650" />

- GPT-4o-mini
  - 입력 토큰: $0.150 / 1M 토큰
  - 출력 토큰: $0.600 / 1M 토큰

- GPT-3.5-turbo-0125
  - 입력 토큰: $0.50 / 1M 토큰
  - 출력 토큰: $1.50 / 1M 토큰

### API Route 사용
클라이언트에서 직접 호출방식은 API 키 노출로 인하여 보안이 위험합니다.
아직은 단순한 구조이지만
요청 횟수 제한, 여러가지의 에러 핸들링들을 통합, 캐싱처리 등
위와 같은 기능들을 쉽게 추가할 수 있도록 확장성을 위해 사용하였습니다.

### openai 인스턴스를 분리
OpenAI 설정을 한 곳에서 관리할 수 있고, 재사용성이 높이기 위해 분리하였습니다.

### Prompt
- System Prompt
AI의 역할과 행동 방식을 정의
응답 형식과 규칙을 설정
전체적인 컨텍스트 제공
세션 전체에 걸쳐 유지되는 지침

- User Content
구체적인 요청/질문
특정 상황에 대한 입력
실제 수행해야 할 작업 명시
각 요청마다 변경될 수 있는 내용

### 요청 흐름

1. **클라이언트 컴포넌트에서 시작**:
```typescript
// InterviewChat.tsx (클라이언트)
const handleGenerateNewQuestion = async () => {
  const question = await generateAnotherQuestionAPI({...});  // api/interview.ts 호출
};
```

2. **API 클라이언트 함수** (`services/api/interview.ts`):
```typescript
export async function generateAnotherQuestionAPI(params) {
  return fetchWithErrorHandling('/api/questions/another', params);  // API Route 호출
}
```

3. **API Route** (`api/questions/another/route.ts`):
```typescript
export async function POST(request: Request) {
  const body = await request.json();
  const question = await generateAnotherQuestion(body);  // services/interview.ts 호출
  return NextResponse.json(question);
}
```

4. **OpenAI 서비스** (`services/interview.ts`):
```typescript
export async function generateAnotherQuestion(params) {
  const completion = await openai.chat.completions.create({...});  // OpenAI API 호출
  return result;
}
```
이렇게 분리하는 이유는 보안과 관심사 분리를 위함입니다.
```
services/
├── api/              # 클라이언트 API 함수 (클라이언트에서 서버로 요청하는 함수들)
│   └── interview.ts  # fetch로 API Route 호출 (Next.js API 엔드포인트)
└── interview.ts      # 서버 사이드 로직 (OpenAI API 호출)
```
```
클라이언트 (React) 
  → services/api (API 클라이언트)
    → API Route (서버)
      → services/interview (OpenAI 로직)
        → OpenAI API
```

https://openai.com/api/pricing/
