### ISSUE TITLE
답변 입력 공통 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by minjeongHEO** [minjeongHEO/Job-Cracker#23]
## ✏️ 기능 설명

<br><br>

## ✅ TODO
- [x] 사용자 답변 입력 UI 
- [x] 동적으로 높이 조절
- [ ] ~브라우저 별 커스텀 스크롤~
<br><br>

## 📕 참고할만한 자료(선택) 

커스텀 스크롤은 브라우저에 따라 적용되는 속성이 다릅니다.
```tsx
/* 스크롤바 스타일 */
    /* Webkit 기반 브라우저 */
    &::-webkit-scrollbar {
      width: 10px;
      cursor: auto;
    }
    &::-webkit-scrollbar-track {
      background: rgba(color('neutral', 'grey'), 0.3);
    }
    /* 스크롤 핸들 */
    &::-webkit-scrollbar-thumb {
      background: rgba(color('neutral', 'grey'), 0.6);
    }
    &::-webkit-scrollbar-thumb:hover {
      background: color('neutral', 'grey')
    }
```
```tsx
 /* firefox 브라우저 */
    ✅scrollbar-width: thin; 
    ❌scrollbar-width: 10px; 

    ✅scrollbar-color: var(--color-neutral-grey) rgba(var(--color-neutral-grey), 0.3);
    ❌scrollbar-color: color('neutral', 'grey') rgba(color('neutral', 'grey'), 0.3);
```
SCSS의 color() 함수와 CSS 변수를 조합하면 Firefox와 Webkit 기반 브라우저 모두에서 동적으로 색상을 관리할 수 있습니다.
하드코딩 없이 중앙 관리된 SCSS 변수를 CSS 변수로 활용하는 것이 유지보수성에 유리하므로 변수를 생성하였습니다.

| Webkit 기반 브라우저 (Chrome, Edge, Safari)|
| --- | 
| ![image](https://github.com/user-attachments/assets/90e745e4-6739-46fa-9b23-7e7be6c4cac6) |

|Firefox 전용 속성 적용 전 | Firefox 전용 속성 적용 후 |
|--- | --- |
| ![image](https://github.com/user-attachments/assets/3356e9dd-9347-4fe7-9ec4-fb608f626da6) | ![image](https://github.com/user-attachments/assets/9cf4af15-d3d4-413f-a84d-57d93c061eae) |
