### ISSUE TITLE
주제 선택 페이지 구현

### ISSUE THREAD

**Issue by minjeongHEO** [minjeongHEO/Job-Cracker#8]
## ✏️ 기능 설명
면접 준비를 위한 주제 선택 플로우를 구현합니다.

<br><br>

## ✅ TODO
- [x] 주제선택 1단계
- [x] 주제선택 2단계
- [x] 상태 관리 전략 결정
- [ ] ~전역으로 상태 관리~
- [x] layout 분리 및 적용
- [x] 전체 선택/해제
- [x] 선택 현황 표시

### 🔍 상태 관리 설계
전역 상태 관리 대신 쿼리 파라미터 방식을 채택했습니다

1. **채택 이유**:
   - 단방향 사용자 플로우 (뒤로가기 불필요하다고 생각)
   - 구현의 단순성
   - URL을 통한 상태 추적 용이
   - 서버 컴포넌트 활용도 증가
   - 전역 상태 관리 불필요

2. **URL 구조 설계**:
```
/interview/select/[분야]/prepare?topics=[주제목록]
```

예시:
```
/interview/select/FrontEnd/prepare?topics=HTML/CSS,JavaScript
/interview/select/FrontEnd/prepare?topics=all
```

### 🏗️ 컴포넌트 구조
- 레이아웃 구성:
  - 공통 타이틀 섹션을 layout 컴포넌트로 분리하여 재사용성 확보

- 렌더링 전략
  - 타이틀 섹션: 서버 컴포넌트(layout)
  - 선택 박스 섹션: 클라이언트 컴포넌트
  - 목적: Next.js의 하이브리드 렌더링 활용

### 💡 설계 결정사항
초기 고려: 긴 URL 길이를 줄이기 위한 인덱스 기반 접근
최종 결정: 쿼리 파라미터에 인덱스 대신 실제 값을 사용
- 더 명확한 의미 전달
- 향상된 유지보수성
- 의미있는 값 전달이 RESTful URL 설계 원칙 준수

<br><br>

## 📕 참고할만한 자료(선택) 
https://nextjs-ko.org/docs/app/api-reference/functions/use-search-params
